### PR TITLE
Attempt at adding PAN16-1

### PR DESCRIPTION
**Pull request by jolny**
I've added most of the files/data needed for the PAN16-1. Should work with this

### CODE REVIEW

**Comment by jolny** [comment]
Confirmed working!

**Comment by jolny** [comment]
@Inversion-NL I've now bumped up the version number in the app.json and README.md, is that enough?

**Comment by Inversion-NL** [comment]
For solving issue https://github.com/Inversion-NL/com.philio/issues/27

**Comment by Inversion-NL** [comment]
Submitted for approval

**Comment by Inversion-NL** [comment]
Thanks @jolny

**Comment by Inversion-NL** [comment]
And published!
Thanks @jolny

**Comment by jolny** [comment]
Thanks :)
I've added the PANxx modules with Z-wave+ now, have found a tester for one of the modules. Will create a new PR when testing is done!

**Comment by Inversion-NL** [comment]
Great!

**Pull request merged**
