### PR TITLE
Add support for PAN11, PAN04, PAN06 Z-wave+ devices

### PR DESCRIPTION
**Pull request by jolny**
I've simply added the device ID:s for PAN11-1x (A, B, D, E that I know of), PAN04-1B and PAN06-1B to the app.json, as the devices have the exact same features besides the Z-wave+ support.
Tested and confirmed working by some people that commented on the app page that were able to help :)

This PR also contains SVG files for PAN16, and I edited the PAN11 and PAN16 names so they also contain their respective product names.

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Great!
Nice work.
So can I submit for approval to the app store or should I wait?

**Comment by jolny** [comment]
Go ahead, I'm not planning to submit anything more the next few days :)

**Comment by Inversion-NL** [comment]
Submitted for approval

**Comment by Inversion-NL** [comment]
And published to the app store!

**Comment by jolny** [comment]
Sweet!
Have a nice weekend :-)


Den 3 nov 2017 2:41 em skrev "Inversion-NL" <notifications@github.com>:

**Pull request merged**
