### PR TITLE
Create PAN08

### PR DESCRIPTION
**Pull request by Drops70**
Add Support for PAN08

### CODE REVIEW

**Comment by Drops70** [comment]
Tried my best based on limited Java knowledge .... Hope this is the right information needed, although I am not sure. I can also provide svg files if of help.

**Comment by Inversion-NL** [comment]
Yes, please

**Comment by Drops70** [comment]
Ok - how to add sv-files? Tried to add, but says svg files are not supported ..

**Comment by Drops70** [comment]
Happy New Year!
As for the svg files the same as for the PAN06-1 can be used. The all have the same housing.
Do you need any more input from my side?

**Comment by Inversion-NL** [comment]
There are no changes in this commit?

**Comment by Drops70** [comment]
"use strict";
var path = require('path');
const ZwaveDriver = require('homey-zwavedriver');
// Product Name:    In Wall roller shutter controller PAN08-1
// Brand Name:    Philio
// Product Line:    Philio Z-Wave Product
// Product Code:    PAN08-1
// Product Version:    1.1

module.exports = new ZwaveDriver(path.basename(__dirname), {
  capabilities: {
    windowcoverings_state: {
      command_class: 'COMMAND_CLASS_SWITCH_BINARY',
      command_get: 'SWITCH_BINARY_GET',
      command_set: 'SWITCH_BINARY_SET',
      command_set_parser: (value) => ({
        'Switch Value': (value > 0) ? 'on/enable' : 'off/disable',
      }),
      command_report: 'SWITCH_BINARY_REPORT',
      command_report_parser: (report, node) => {
        switch (report.Value) {
          case 'on/enable':
            return 'up';
          case 'off/disable':
            return 'down';
          default:
            return 'idle';
        }
      },
    },  
    dim: {
      command_class: 'COMMAND_CLASS_SWITCH_MULTILEVEL',
      command_get: 'SWITCH_MULTILEVEL_GET',
      command_set: 'SWITCH_MULTILEVEL_SET',
      command_set_parser: (value, node) => {
        if (value >= 1) {
          value = 0.99;
        }
        return {
          'Value': value * 100,
          'Dimming Duration': 'Factory default',
        };
      },
      command_report: 'SWITCH_MULTILEVEL_REPORT',
      command_report_parser: (report, node) => {
      },
    },
   },
    settings: {
        "modeSelection": {
            "index": 1,
            "size": 1
        },
        "edgePulseedgeToggleMode": {
            "index": 2,
            "size": 1
        },
        "restoreSwitchStateMode": {
            "index": 3,
            "size": 1
        },
        "autoOffTimer": {
            "index": 4,
            "size": 2
        },
        "rfOffCommand ": {
            "index": 5,
            "size": 1
        },
        "existenceEndpoint3 ": {
            "index": 6,
            "size": 1
        }
    }
});
``

**Comment by Drops70** [comment]
Sorry, try to upload the new driver, but I always fail ...

**Pull request merged**
