### PR TITLE
Improvements of drivers

### PR DESCRIPTION
**Pull request by superspyrene**
Hi,

I did some improvements on the drivers.
I split this one in two version, i forgot to create a pull request for 0.14

If its better to combine them in one version, let me know.

+0.0.15
* Fix that onOff is not correctly set after restart
* Added missing Voltage and Amp Meter for the PAN11-1
* Update z-wave drivers (1.1.8)

0.0.14
* Added missing parameters for the PAN06-1
* Added missing parameters for the PAN11-1
* Add support for PAN04-1 In Wall Dual relay with meter
* Fix wrong image for learn mode
* Update z-wave drivers (1.1.4)
* Added battery polling when awake for PSM02/PSR04/PST02-A/PST02-C
* Added fix for settings for PAN11/PAN04/PAN06

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Great! Thanks

**Comment by Inversion-NL** [comment]
Could you please add the PNG images as shown in the screenshot of the app store submission error below, please?

P.s.
You can verify the app store requirements in the Athom CLI by using: `athom project --validate-app-store`
As described here:
[Athom library: appstore requirements](https://developers.athom.com/library/appstore/)


philio _ athom apps

**Comment by Inversion-NL** [comment]
Already received a pull request which has those icons. Thanks for the PR!

**Comment by superspyrene** [comment]
Sorry for the late reaction.
Next time i will check it with this command if it meets the requirements.

**Pull request merged**
