### PR TITLE
"small" fixup to be able to install it again.

### PR DESCRIPTION
**Pull request by caseda**
this should fix all issues the validator was throwing letting it be able to install on homey v2

also fixed the PAN08-01 implementation, this could have _Never_ worked for the guy that added the driver

also changed the app to the build in composer plugin homey uses, this will make it a lot easier to convert the app to SDKv2 with this many devices and find and fix small issues in the app .
(which is also coming up, but would suggest keeping the SDKv2 rewrite in a beta channel first, this one can go to the app-store immediately as it doesn't contain any functional changes, except for the PAN08 implementation of course)

the composer runs automatically as soon as you run/install/validate the app via cli, or run `homey app build`
it will overwrite all capabilities/drivers/flows in the app.json so nothing can be added/changed manually in the app.json, needs to be done in the correspondig /drivers/ID/ folder (driver.compose.json & driver.settings.compose.json & driver.flow.compose.json)

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Hmm, I'll have to check, one of the assets is missing:

screenshot_20181228-141405

**Comment by caseda** [comment]
ah i see the mistake :p missing the `-1` in the paths of the images

**Comment by Inversion-NL** [comment]
Yes I'm already uploading an update

**Comment by Inversion-NL** [comment]
Send for approval in the Homey app store

**Comment by Inversion-NL** [comment]
> this should fix all issues the validator was throwing letting it be able to install on homey v2
> 
> also fixed the PAN08-01 implementation, this could have _Never_ worked for the guy that added the driver
> 
> also changed the app to the build in composer plugin homey uses, this will make it a lot easier to convert the app to SDKv2 with this many devices and find and fix small issues in the app .
> (which is also coming up, but would suggest keeping the SDKv2 rewrite in a beta channel first, this one can go to the app-store immediately as it doesn't contain any functional changes, except for the PAN08 implementation of course)
> 
> the composer runs automatically as soon as you run/install/validate the app via cli, or run `homey app build`
> it will overwrite all capabilities/drivers/flows in the app.json so nothing can be added/changed manually in the app.json, needs to be done in the correspondig /drivers/ID/ folder (driver.compose.json & driver.settings.compose.json & driver.flow.compose.json)

I wish there was an V1 to V2 migrition guide.
Havent been keeping up the changes the last year so I got the feeling I need to learn it all over again.

**Comment by caseda** [comment]
even if there was a migration guide it is still a lot of manual work unfortunately 😛.

but you'll see what has changed soon enough, it became a lot easier if the device is relatively normal, luckily philio has mostly normal devices

**Comment by Inversion-NL** [comment]
Ah great, I'd like to learn how to do it.

**Comment by Inversion-NL** [comment]
Update approved and submitted to the store.
Thanks @caseda

**Pull request merged**
