### PR TITLE
Added support for PAN06-1

### PR DESCRIPTION
**Pull request by superspyrene**
* Added support for PAN06-1
* Removed some debug markers

### CODE REVIEW

**Comment by Inversion-NL** [comment]
Thanks!

**Comment by gratjetost** [comment]
great!! thank you. maybe also time for the PAN04??

**Comment by superspyrene** [comment]
@gratjetost If you can provide me the information for the PAN04. The information that i need can be found under "Node Information" in the config popup of the z-wave sensor.

I will add the missing parameters for the pan06 and fix the wrong image that i forgot to change.

**Comment by gratjetost** [comment]
pan04_node_info

@superspyrene here is the node information. 
and great thanks for the help!

**Comment by superspyrene** [comment]
@gratjetost Can you test the pan04 from my repository?

**Comment by gratjetost** [comment]
@superspyrene I can't find it in the repository. is it located somewhere else?

**Comment by Inversion-NL** [comment]
https://github.com/superspyrene/com.philio

**Pull request merged**
